name: tests

on:
  push:
    paths:
      - "Formula/**"
  pull_request:
    paths:
      - "Formula/**"

jobs:
  test:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - name: Tap this repo locally
        run: brew tap queq-co/tap "$GITHUB_WORKSPACE"

      - name: brew audit
        run: brew audit --strict queq-co/tap/tuigram

      - name: brew style
        run: brew style queq-co/tap/tuigram

      - name: brew install
        run: brew install queq-co/tap/tuigram

      - name: brew test
        run: brew test queq-co/tap/tuigram
